[package]
name = "parallel_levenshtein"
version = "0.1.0"
authors = ["Riccardo Zaglia <riccardo.zaglia5@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.59"

[dependencies]
mpi = "0.5.4"